# This is a Docker Compose manifest file, used by the CLI tool `docker-compose`.
# Read more: https://docs.docker.com/compose/
version: "3"
services:
  # read more: http://postgrest.org
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    links:
      - db:db
    env_file:
      - ./postgrest.env
    depends_on:
      - db
  # the db/ subdirectory has relevant files for this service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432
    env_file:
      - ./db.env
    # the host OS's ./db/data is mounted on the container's
    # /var/lib/postgresql/data path. This means that you can go back up the
    # ./db/data folder or delete it to effectively "reset" this service to
    # scratch.
    volumes:
      - ./db/data:/var/lib/postgresql/data
