version: "3"
services:
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    links:
      - db:db
    env_file:
      - ./postgrest.env
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432
    env_file:
      - ./db.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
